services:
  # -----------------------------
  # MySQL
  # -----------------------------
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: centralized_data
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

  # -----------------------------
  # Keycloak
  # -----------------------------
  keycloak-server:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak-server
    command: [ "start-dev", "--http-relative-path=/" ]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin@123}
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - springnet

  # -----------------------------
  # OpenTelemetry Backend (Jaeger)
  # -----------------------------
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - springnet

volumes:
  mysql_data:
  keycloak_data:

networks:
  springnet:
    driver: bridge

