apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  annotations:
    argocd-image-updater.argoproj.io/image-list: "devopspaxarisglobalrepo/apigateway"
    argocd-image-updater.argoproj.io/apigateway.update-strategy: latest
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: api-gateway
          image: "devopspaxarisglobalrepo/apigateway:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: PROJECT_MANAGEMENT_BASE_URL
              value: http://product-management-service:8088
            - name: IDENTITY_SERVICE_URL
              value: http://identity-service:8087
            - name: KEYCLOAK_BASE_URL
              value: http://keycloak:8080
            - name: GATEWAY_CORS_ALLOWED_ORIGINS
              value: http://localhost:4200,http://127.0.0.1:4200
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318/v1/traces

---
