apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto1775829251-admin-autofront-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/auto1775829251-admin-autofront-frontend
    argocd-image-updater.argoproj.io/auto1775829251-admin-autofront-frontend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto1775829251-admin-autofront-frontend
  template:
    metadata:
      labels:
        app: auto1775829251-admin-autofront-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: auto1775829251-admin-autofront-frontend
          image: devopspaxarisglobalrepo/auto1775829251-admin-autofront-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto1775829251-admin-autofront-frontend
spec:
  selector:
    app: auto1775829251-admin-autofront-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
