apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "REPLACE_DOCKERHUB_USERNAME",
          "password": "REPLACE_DOCKERHUB_PASSWORD",
          "auth": "REPLACE_BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
