apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/identity-service
    argocd-image-updater.argoproj.io/identity-service.update-strategy: latest
spec:
  selector:
    matchLabels:
      app: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: identity-service
          image: devopspaxarisglobalrepo/identity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/centralized_data?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: KEYCLOAK_BASE_URL
              value: http://keycloak:8080
            - name: PROJECT_MANAGER_URL
              value: http://product-management-service:8088
            - name: KEYCLOAK_REALM
              value: master
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin@123
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318/v1/traces
            - name: IDENTITY_JWT_ISSUER_HOST_REWRITE_TO
              value: keycloak
            - name: ALLOWED_ORIGINS
              value: "*"
            - name: ALLOWED_METHODS
              value: "*"
            - name: ALLOWED_HEADERS
              value: "*"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 32087
  type: NodePort