apiVersion: apps/v1
kind: Deployment
metadata:
  name: paxaris-test-admin-testapp-api-check-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/paxaris_test-admin-testapp-api-check-frontend
    argocd-image-updater.argoproj.io/paxaris_test-admin-testapp-api-check-frontend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paxaris-test-admin-testapp-api-check-frontend
  template:
    metadata:
      labels:
        app: paxaris-test-admin-testapp-api-check-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: paxaris-test-admin-testapp-api-check-frontend
          image: devopspaxarisglobalrepo/paxaris_test-admin-testapp-api-check-frontend-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: paxaris-test-admin-testapp-api-check-frontend
spec:
  selector:
    app: paxaris-test-admin-testapp-api-check-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
