apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paxarisglobal-admin-yatrifytest8-backend-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paxarisglobal-admin-yatrifytest8-backend-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paxarisglobal-admin-yatrifytest8-backend-postgres
  template:
    metadata:
      labels:
        app: paxarisglobal-admin-yatrifytest8-backend-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: yatrify
            - name: POSTGRES_USER
              value: yatrify_user
            - name: POSTGRES_PASSWORD
              value: yatrify_pass
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paxarisglobal-admin-yatrifytest8-backend-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: paxarisglobal-admin-yatrifytest8-backend-postgres
spec:
  selector:
    app: paxarisglobal-admin-yatrifytest8-backend-postgres
  ports:
    - port: 5432
      targetPort: 5432
