apiVersion: apps/v1
kind: Deployment
metadata:
  name: paxarisglobal-admin-yatrifytest-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/paxarisglobal-admin-yatrifytest-frontend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paxarisglobal-admin-yatrifytest-frontend
  template:
    metadata:
      labels:
        app: paxarisglobal-admin-yatrifytest-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: paxarisglobal-admin-yatrifytest-frontend
          image: "devopspaxarisglobalrepo/paxarisglobal-admin-yatrifytest-frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: paxarisglobal-admin-yatrifytest-frontend
spec:
  selector:
    app: paxarisglobal-admin-yatrifytest-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32104
  type: NodePort
