apiVersion: apps/v1
kind: Deployment
metadata:
  name: paxarisglobal-admin-yatrify-backend-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paxarisglobal-admin-yatrify-backend-redis
  template:
    metadata:
      labels:
        app: paxarisglobal-admin-yatrify-backend-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server"]
---
apiVersion: v1
kind: Service
metadata:
  name: paxarisglobal-admin-yatrify-backend-redis
spec:
  selector:
    app: paxarisglobal-admin-yatrify-backend-redis
  ports:
    - port: 6379
      targetPort: 6379
