apiVersion: apps/v1
kind: Deployment
metadata:
  name: paxarisglobaltest9-admin-autoe2e07865-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=devopspaxarisglobalrepo/paxarisglobaltest9-admin-autoe2e07865-backend
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paxarisglobaltest9-admin-autoe2e07865-backend
  template:
    metadata:
      labels:
        app: paxarisglobaltest9-admin-autoe2e07865-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: paxarisglobaltest9-admin-autoe2e07865-backend
          image: devopspaxarisglobalrepo/paxarisglobaltest9-admin-autoe2e07865-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
---
apiVersion: v1
kind: Service
metadata:
  name: paxarisglobaltest9-admin-autoe2e07865-backend
spec:
  selector:
    app: paxarisglobaltest9-admin-autoe2e07865-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
