apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-frontend
spec:
  selector:
    matchLabels:
      app: python-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: python-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: python-frontend
          image: "devopspaxarisglobalrepo/python_foundry_frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-frontend
spec:
  selector:
    app: python-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
