apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke1775826870-admin-prehitcheck-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/smoke1775826870-admin-prehitcheck-frontend
    argocd-image-updater.argoproj.io/smoke1775826870-admin-prehitcheck-frontend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smoke1775826870-admin-prehitcheck-frontend
  template:
    metadata:
      labels:
        app: smoke1775826870-admin-prehitcheck-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: smoke1775826870-admin-prehitcheck-frontend
          image: devopspaxarisglobalrepo/smoke1775826870-admin-prehitcheck-frontend-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smoke1775826870-admin-prehitcheck-frontend
spec:
  selector:
    app: smoke1775826870-admin-prehitcheck-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
