apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke1775827830-admin-readyhit2-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/smoke1775827830-admin-readyhit2-backend
    argocd-image-updater.argoproj.io/smoke1775827830-admin-readyhit2-backend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smoke1775827830-admin-readyhit2-backend
  template:
    metadata:
      labels:
        app: smoke1775827830-admin-readyhit2-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: smoke1775827830-admin-readyhit2-backend
          image: devopspaxarisglobalrepo/smoke1775827830-admin-readyhit2-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: smoke1775827830-admin-readyhit2-backend
spec:
  selector:
    app: smoke1775827830-admin-readyhit2-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
