apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vipul-admin-backend-test-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/test-vipul-admin-backend_test-frontend
    argocd-image-updater.argoproj.io/test-vipul-admin-backend_test-frontend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-vipul-admin-backend-test-frontend
  template:
    metadata:
      labels:
        app: test-vipul-admin-backend-test-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: test-vipul-admin-backend-test-frontend
          image: devopspaxarisglobalrepo/test-vipul-admin-backend-test-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-vipul-admin-backend-test-frontend
spec:
  selector:
    app: test-vipul-admin-backend-test-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
