apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_vipul-admin-test6-test6-vipul6-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: devopspaxarisglobalrepo/test_vipul-admin-test6-test6-vipul6-backend
    argocd-image-updater.argoproj.io/test_vipul-admin-test6-test6-vipul6-backend.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test_vipul-admin-test6-test6-vipul6-backend
  template:
    metadata:
      labels:
        app: test_vipul-admin-test6-test6-vipul6-backend
    spec:
      containers:
        - name: test_vipul-admin-test6-test6-vipul6-backend
          image: devopspaxarisglobalrepo/test_vipul-admin-test6-test6-vipul6-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: test_vipul-admin-test6-test6-vipul6-backend
spec:
  selector:
    app: test_vipul-admin-test6-test6-vipul6-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
