apiVersion: apps/v1
kind: Deployment
metadata:
  name: vipultest-admin-test5-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/vipultest-admin-test5-frontend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vipultest-admin-test5-frontend
  template:
    metadata:
      labels:
        app: vipultest-admin-test5-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: vipultest-admin-test5-frontend
          image: "devopspaxarisglobalrepo/vipultest-admin-test5-frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vipultest-admin-test5-frontend
spec:
  selector:
    app: vipultest-admin-test5-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
