apiVersion: apps/v1
kind: Deployment
metadata:
  name: vipultest-admin-test5-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/vipultest-admin-test5-backend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vipultest-admin-test5-backend
  template:
    metadata:
      labels:
        app: vipultest-admin-test5-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: vipultest-admin-test5-backend
          image: "devopspaxarisglobalrepo/vipultest-admin-test5-backend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
---
apiVersion: v1
kind: Service
metadata:
  name: vipultest-admin-test5-backend
spec:
  selector:
    app: vipultest-admin-test5-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
