apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatrify-admin-yatrifyproduct-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/yatrify-admin-yatrifyproduct-backend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yatrify-admin-yatrifyproduct-backend
  template:
    metadata:
      labels:
        app: yatrify-admin-yatrifyproduct-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h $PGHOST -p 5432 -U $PGUSER; do echo waiting for postgres; sleep 2; done
          env:
            - name: PGHOST
              value: yatrify-admin-yatrifyproduct-postgres
            - name: PGUSER
              value: yatrify_user
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: yatrify-admin-yatrifyproduct-backend
          image: "devopspaxarisglobalrepo/yatrify-admin-yatrifyproduct-backend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_URL
              value: jdbc:postgresql://yatrify-admin-yatrifyproduct-postgres:5432/yatrify
            - name: DB_USERNAME
              value: yatrify_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yatrify-admin-yatrifyproduct-db-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: yatrify-admin-yatrifyproduct-redis
            - name: REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: PAXARIS_GATEWAY_URL
              value: http://api-gateway:8085
---
apiVersion: v1
kind: Service
metadata:
  name: yatrify-admin-yatrifyproduct-backend
spec:
  selector:
    app: yatrify-admin-yatrifyproduct-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32401
  type: NodePort
