apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatrify-admin-testyatrify-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/yatrify-admin-testyatrify-backend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yatrify-admin-testyatrify-backend
  template:
    metadata:
      labels:
        app: yatrify-admin-testyatrify-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h yatrify-admin-testyatrify-backend-postgres -p 5432 -U yatrify_user; do echo waiting for postgres; sleep 2; done
      containers:
        - name: yatrify-admin-testyatrify-backend
          image: "devopspaxarisglobalrepo/yatrify-admin-testyatrify-backend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_URL
              value: jdbc:postgresql://yatrify-admin-testyatrify-backend-postgres:5432/yatrify
            - name: DB_USERNAME
              value: yatrify_user
            - name: DB_PASSWORD
              value: yatrify_pass
            - name: REDIS_HOST
              value: yatrify-admin-testyatrify-backend-redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: yatrify-admin-testyatrify-backend
spec:
  selector:
    app: yatrify-admin-testyatrify-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32402
  type: NodePort
