apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatrify-admin-yatrifyproduct-frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app=devopspaxarisglobalrepo/yatrify-admin-yatrifyproduct-frontend"
    argocd-image-updater.argoproj.io/app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yatrify-admin-yatrifyproduct-frontend
  template:
    metadata:
      labels:
        app: yatrify-admin-yatrifyproduct-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: yatrify-admin-yatrifyproduct-frontend
          image: "devopspaxarisglobalrepo/yatrify-admin-yatrifyproduct-frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yatrify-admin-yatrifyproduct-frontend
spec:
  selector:
    app: yatrify-admin-yatrifyproduct-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32101
  type: NodePort
