apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: paxarisglobaltest9-admin-codetest174812-backend-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/PaxarisGlobal/paxarisglobaltest9-admin-codetest174812-backend.git
        targetRevision: main
        path: k8
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
