apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: smoke1775826870-admin-prehitcheck-frontend-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/PaxarisGlobal/smoke1775826870-admin-prehitcheck-frontend.git
        targetRevision: main
        path: k8
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
